#-------------------------------------------------------------------------------------------
# Simple makefile for managing the tests subdirectory. 
#-------------------------------------------------------------------------------------------

.PHONY: all
all:

.PHONY: clean
clean:
	rm -rf *.log *_results *.rslts *_maqao .DS_Store *.core

